import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#111827' },
  calculator: { flex: 1, width: '100%', maxWidth: 720, alignSelf: 'center', paddingHorizontal: 20, paddingBottom: 20, justifyContent: 'flex-end' },
  title: { color: '#94a3b8', fontSize: 12, fontWeight: '700', letterSpacing: 2 },
  titleButton: { alignSelf: 'flex-start', marginBottom: 20 },
  display: { minHeight: 150, justifyContent: 'flex-end', alignItems: 'flex-end', paddingHorizontal: 8, paddingBottom: 24 },
  expression: { color: '#94a3b8', fontSize: 24, marginBottom: 8 },
  displayText: { color: '#f8fafc', fontSize: 68, fontWeight: '300', maxWidth: '100%' },
  keypadLayout: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  keypad: { flex: 1, gap: 12 },
  keyRow: { flexDirection: 'row', gap: 12 },
  key: { flex: 1, aspectRatio: 1, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#273449' },
  operator: { backgroundColor: '#f59e0b' },
  function: { backgroundColor: '#cbd5e1' },
  utilityColumn: { width: '19%', flexShrink: 0, gap: 12 },
  utilityKey: { width: '100%', aspectRatio: 1, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  utilityKeyGreen: { backgroundColor: '#22c55e' },
  utilityKeyRed: { backgroundColor: '#ef4444' },
  utilityKeyPurple: { backgroundColor: '#a812f4' },
  utilityKeyBlue: { backgroundColor: '#0862f1' },
  pressed: { opacity: 0.65, transform: [{ scale: 0.97 }] },
  keyText: { color: '#fff', fontSize: 28, fontWeight: '500' },
  functionText: { color: '#172033' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.72)', justifyContent: 'center', padding: 20 },
  tableModalBackdrop: { padding: 0 },
  listPanel: { width: '100%', maxWidth: 520, maxHeight: '80%', alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 8, padding: 20 },
  tablePanel: { width: '100%', height: '100%', maxHeight: '100%', alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 0, padding: 20 },
  savePanel: { width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 8, padding: 20 },
  listTitle: { color: '#f8fafc', fontSize: 22, fontWeight: '700', marginBottom: 16 },
  listScroll: { marginBottom: 16 },
  tableVerticalScroll: { flex: 1, marginBottom: 16, minHeight: 0 },
  tableScroll: { flex: 1, marginBottom: 0, minHeight: 0 },
  tableActions: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  tableActionButton: { flex: 1 },
  tableHeaderRow: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: '#94a3b8', backgroundColor: '#0f172a' },
  tableBodyRow: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: '#475569' },
  tableHeaderCell: { padding: 10, borderRightWidth: 2, borderRightColor: '#64748b', backgroundColor: '#0f172a' },
  tableHeaderText: { fontWeight: '700', color: '#f8fafc', textAlign: 'center' },
  tableCell: { padding: 10, borderRightWidth: 2, borderRightColor: '#64748b', backgroundColor: 'rgba(15, 23, 42, 0.9)', justifyContent: 'flex-start' },
  tableCellText: { color: '#e2e8f0', textAlign: 'center', flexShrink: 1 },
  nameColumn: { width: 150 },
  infoColumn: { width: 220 },
  typeColumn: { width: 120 },
  saveInput: { backgroundColor: '#0f172a', borderColor: '#475569', borderWidth: 1, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 10, color: '#f8fafc', fontSize: 16, marginBottom: 12 },
  saveSuggestions: { backgroundColor: '#0f172a', borderRadius: 6, borderColor: '#475569', borderWidth: 1, overflow: 'hidden', marginBottom: 16 },
  suggestionItem: { paddingHorizontal: 12, paddingVertical: 10, borderBottomColor: '#334155', borderBottomWidth: 1 },
  suggestionText: { color: '#e2e8f0', fontSize: 15 },
  saveActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  savedItem: { borderBottomColor: '#475569', borderBottomWidth: 1, paddingVertical: 12, borderRadius: 6, paddingHorizontal: 10, marginBottom: 8 },
  savedItemGreen: { backgroundColor: 'rgba(34, 197, 94, 0.18)' },
  savedItemRed: { backgroundColor: 'rgba(239, 68, 68, 0.18)' },
  savedItemPurple: { backgroundColor: 'rgba(139, 92, 246, 0.18)' },
  savedItemBlue: { backgroundColor: 'rgba(59, 130, 246, 0.18)' },
  savedTitle: { color: '#86efac', fontSize: 18, fontWeight: '700', marginBottom: 4 },
  savedExpression: { color: '#cbd5e1', fontSize: 15, marginBottom: 4 },
  savedValue: { color: '#f8fafc', fontSize: 20 },
  savedMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  savedDate: { color: '#f8fafc', fontSize: 12, opacity: 0.85 },
  savedType: { color: '#f8fafc', fontSize: 11, fontWeight: '700', opacity: 0.9 },
  emptyList: { color: '#94a3b8', fontSize: 16, paddingVertical: 20 },
  closeButton: { alignItems: 'center', backgroundColor: '#22c55e', borderRadius: 5, paddingVertical: 12, flex: 1 },
  listCloseButton: { width: '100%', alignSelf: 'stretch', flex: 0 },
  cancelButton: { backgroundColor: '#64748b' },
  saveButton: { backgroundColor: '#22c55e' },
  closeButtonText: { color: '#052e16', fontSize: 16, fontWeight: '700' },
});
