import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#111827' },
  calculator: { flex: 1, width: '100%', maxWidth: 720, alignSelf: 'center', paddingHorizontal: 20, paddingBottom: 20, justifyContent: 'flex-end' },
  title: { color: '#94a3b8', fontSize: 12, fontWeight: '700', letterSpacing: 2 },
  titleButton: { alignSelf: 'flex-start', marginBottom: 20 },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  authButton: { backgroundColor: '#334155', borderRadius: 5, paddingHorizontal: 12, paddingVertical: 8, marginBottom: 20 },
  authButtonText: { color: '#f8fafc', fontSize: 13, fontWeight: '700' },
  display: { minHeight: 150, justifyContent: 'flex-end', alignItems: 'flex-end', paddingHorizontal: 8, paddingBottom: 24 },
  expression: { color: '#94a3b8', fontSize: 24, marginBottom: 8 },
  displayText: { color: '#f8fafc', fontSize: 68, fontWeight: '300', maxWidth: '100%' },
  keypadLayout: { width: '100%', flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  keypad: { flex: 1, gap: 12 },
  keyRow: { flexDirection: 'row', gap: 12 },
  key: { flex: 1, aspectRatio: 1, borderRadius: 5, alignItems: 'center', justifyContent: 'center', backgroundColor: '#273449' },
  operator: { backgroundColor: '#f59e0b' },
  function: { backgroundColor: '#cbd5e1' },
  utilityColumn: { width: '19%', flexShrink: 0, gap: 12 },
  utilityKey: { width: '100%', aspectRatio: 1, borderRadius: 5, alignItems: 'center', justifyContent: 'center' },
  utilityKeyGreen: { backgroundColor: '#22c55e' },
  utilityKeyRed: { backgroundColor: '#ef4444' },
  utilityKeyPurple: { backgroundColor: '#a812f4' },
  utilityKeyBlue: { backgroundColor: '#0862f1' },
  pressed: { opacity: 0.8 },
  keyText: { color: '#fff', fontSize: 28, fontWeight: '500' },
  functionText: { color: '#172033' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.72)', justifyContent: 'center', padding: 20 },
  keyboardAvoidingView: { flex: 1 },
  tableModalBackdrop: { padding: 0 },
  listPanel: { width: '100%', maxWidth: 520, maxHeight: '80%', alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 8, padding: 20 },
  tablePanel: { width: '100%', height: '100%', maxHeight: '100%', alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 0, padding: 20, paddingBottom: 28 },
  savePanel: { width: '100%', maxWidth: 520, alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 8, padding: 20 },
  authPanel: { width: '100%', maxWidth: 420, alignSelf: 'center', backgroundColor: '#1e293b', borderRadius: 8, padding: 20 },
  authInput: { backgroundColor: '#0f172a', borderColor: '#475569', borderWidth: 1, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 11, color: '#f8fafc', fontSize: 16, marginBottom: 12 },
  authActions: { gap: 10, marginBottom: 12 },
  authActionButton: { minHeight: 48, borderRadius: 5, paddingHorizontal: 12, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  authEmailButton: { backgroundColor: '#22c55e' },
  googleButton: { backgroundColor: '#4285f4' },
  authModeButton: { alignItems: 'center', paddingVertical: 12 },
  authModeText: { color: '#93c5fd', fontSize: 14, fontWeight: '600' },
  authHint: { color: '#fbbf24', fontSize: 13, lineHeight: 19, marginBottom: 12 },
  disabledButton: { opacity: 0.45 },
  tableTopHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, flexWrap: 'wrap', gap: 8 },
  tableTitleGroup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  listTitle: { color: '#f8fafc', fontSize: 22, fontWeight: '700', marginBottom: 16 },
  tableTitle: { marginBottom: 0 },
  searchIconButton: { width: 36, height: 36, borderRadius: 6, alignItems: 'center', justifyContent: 'center', backgroundColor: '#334155', borderWidth: 1, borderColor: '#475569' },
  searchIconButtonActive: { backgroundColor: '#2563eb', borderColor: '#60a5fa' },
  searchIcon: { color: '#f8fafc', fontSize: 25, lineHeight: 28, fontWeight: '700' },
  searchInputContainer: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 180, maxWidth: 300 },
  tableSearchInput: { flex: 1, height: 36, backgroundColor: '#0f172a', borderColor: '#475569', borderWidth: 1, borderRadius: 6, paddingHorizontal: 10, paddingRight: 34, color: '#f8fafc', fontSize: 14 },
  searchClearButton: { position: 'absolute', right: 2, width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  searchClearText: { color: '#cbd5e1', fontSize: 22, lineHeight: 24 },
  dateDropdownButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#0f172a', borderWidth: 1, borderColor: '#475569', borderRadius: 6, paddingHorizontal: 12, paddingVertical: 8, gap: 8 },
  dateDropdownButtonText: { color: '#f8fafc', fontSize: 14, fontWeight: '600' },
  dateDropdownArrow: { color: '#94a3b8', fontSize: 12 },
  dropdownBackdrop: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.75)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  dropdownPanel: { width: '100%', maxWidth: 440, backgroundColor: '#1e293b', borderRadius: 10, padding: 20, borderWidth: 1, borderColor: '#475569' },
  dropdownTitle: { fontSize: 17, fontWeight: '700', color: '#f8fafc', marginBottom: 12 },
  rangeContainer: { marginBottom: 12, gap: 10 },
  rangeCol: { gap: 4 },
  rangeLabel: { fontSize: 13, fontWeight: '600', color: '#cbd5e1' },
  rangeScroll: { flexDirection: 'row', flexGrow: 0 },
  rangePill: { backgroundColor: '#0f172a', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1, borderColor: '#475569', marginRight: 6 },
  rangePillSelected: { backgroundColor: '#2563eb', borderColor: '#3b82f6' },
  rangePillText: { color: '#94a3b8', fontSize: 12, fontWeight: '500' },
  rangePillTextSelected: { color: '#ffffff', fontWeight: '700' },
  quickActionsRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  quickActionButton: { flex: 1, backgroundColor: '#334155', borderRadius: 6, paddingVertical: 8, alignItems: 'center' },
  quickActionText: { color: '#f8fafc', fontSize: 12, fontWeight: '600' },
  listSubtitle: { color: '#94a3b8', fontSize: 12, fontWeight: '600', marginBottom: 8 },
  dropdownItem: { paddingVertical: 10, paddingHorizontal: 14, borderRadius: 6, marginBottom: 6, backgroundColor: '#0f172a' },
  dropdownItemSelected: { backgroundColor: '#1e3a8a', borderWidth: 1, borderColor: '#3b82f6' },
  dropdownItemText: { color: '#e2e8f0', fontSize: 14, fontWeight: '500' },
  dropdownItemTextSelected: { color: '#ffffff', fontWeight: '700' },
  dropdownCloseButton: { backgroundColor: '#22c55e', borderRadius: 6, paddingVertical: 12, alignItems: 'center', marginTop: 12 },
  dropdownCloseButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  listScroll: { marginBottom: 16 },
  tableHeaderScroll: { flexGrow: 0, flexShrink: 0 },
  tableVerticalScroll: { flex: 1, marginBottom: 16, minHeight: 0 },
  tableScroll: { flexGrow: 0, flexShrink: 0, marginBottom: 0, minHeight: 0 },
  tableActions: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  tableFooter: { flexShrink: 0, paddingBottom: 4 },
  tableActionButton: { flex: 1 },
  csvButton: { backgroundColor: '#0f766e' },
  driveButton: { backgroundColor: '#2563eb' },
  tableHeaderRow: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: '#94a3b8', backgroundColor: '#0f172a' },
  tableBodyRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#475569' },
  tableTotalRow: { flexDirection: 'row', borderTopWidth: 2, borderTopColor: '#94a3b8', backgroundColor: 'rgba(148, 163, 184, 0.12)' },
  tableHeaderCell: { padding: 8, borderRightWidth: 1, borderRightColor: '#64748b', backgroundColor: '#0f172a', justifyContent: 'center' },
  tableHeaderText: { fontWeight: '700', color: '#f8fafc', textAlign: 'center', fontSize: 13 },
  headerCred: { backgroundColor: '#7f1d1d' },
  headerFact: { backgroundColor: '#581c87' },
  headerFcash: { backgroundColor: '#1e3a8a' },
  tableCell: { padding: 4, borderRightWidth: 1, borderRightColor: '#475569', backgroundColor: 'rgba(15, 23, 42, 0.75)', justifyContent: 'center', minHeight: 54 },
  tableCellText: { color: '#e2e8f0', textAlign: 'center', flexShrink: 1 },
  cellInput: { color: '#f8fafc', fontSize: 13, paddingHorizontal: 8, paddingVertical: 6, minHeight: 34, height: 34, backgroundColor: 'rgba(30, 41, 59, 0.8)', borderRadius: 4, borderWidth: 1, borderColor: '#334155', includeFontPadding: false },
  cellInputNumber: { textAlign: 'right', fontWeight: '600', paddingRight: 10 },
  cellDateText: { color: '#94a3b8', fontSize: 9, paddingHorizontal: 4, marginTop: 2 },
  cellInfoTotal: { color: '#86efac', fontSize: 11, fontWeight: '700', marginTop: 6, paddingHorizontal: 8, lineHeight: 14 },
  totalSummaryCell: { minHeight: 44 },
  totalSummaryLabel: { color: '#f8fafc', fontSize: 12, fontWeight: '700', textAlign: 'right', paddingRight: 8 },
  totalSummaryValue: { color: '#f8fafc', fontSize: 12, fontWeight: '700', textAlign: 'right', paddingRight: 8 },
  nameColumn: { width: 160 },
  infoColumn: { width: 200 },
  commentsColumn: { width: 180 },
  credColumn: { width: 115 },
  factColumn: { width: 115 },
  fcashColumn: { width: 115 },
  actionColumn: { width: 44, alignItems: 'center', justifyContent: 'center' },
  shareCellRow: { width: '100%', flexDirection: 'row', alignItems: 'center', gap: 4, minWidth: 0 },
  nameInput: { flex: 1, minWidth: 0 },
  shareRowButton: { width: 28, height: 28, borderRadius: 4, backgroundColor: '#2563eb', borderWidth: 1, borderColor: '#60a5fa', justifyContent: 'center', alignItems: 'center', padding: 0 },
  shareRowButtonText: { color: '#ffffff', fontSize: 16, lineHeight: 18, fontWeight: '700' },
  addRowButton: { backgroundColor: '#3b82f6', borderRadius: 5, paddingVertical: 12, alignItems: 'center', flex: 1 },
  addRowButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  deleteButton: { width: 26, height: 26, borderRadius: 13, backgroundColor: 'rgba(239, 68, 68, 0.25)', justifyContent: 'center', alignItems: 'center', alignSelf: 'center' },
  deleteButtonText: { color: '#ef4444', fontSize: 13, fontWeight: '700' },
  saveInput: { backgroundColor: '#0f172a', borderColor: '#475569', borderWidth: 1, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 10, color: '#f8fafc', fontSize: 16, marginBottom: 12 },
  saveSuggestions: { backgroundColor: '#0f172a', borderRadius: 6, borderColor: '#475569', borderWidth: 1, overflow: 'hidden', marginBottom: 16 },
  suggestionItem: { paddingHorizontal: 12, paddingVertical: 10, borderBottomColor: '#334155', borderBottomWidth: 1 },
  suggestionText: { color: '#e2e8f0', fontSize: 15 },
  saveActions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  savedItem: { borderBottomColor: '#475569', borderBottomWidth: 1, paddingVertical: 12, borderRadius: 6, paddingHorizontal: 10, marginBottom: 8 },
  savedItemGreen: { backgroundColor: 'rgba(34, 197, 94, 0.18)' },
  savedItemRed: { backgroundColor: 'rgba(239, 68, 68, 0.18)' },
  savedItemPurple: { backgroundColor: 'rgba(139, 92, 246, 0.18)' },
  savedItemBlue: { backgroundColor: 'rgba(59, 130, 246, 0.18)' },
  savedTitle: { color: '#86efac', fontSize: 18, fontWeight: '700', marginBottom: 4 },
  savedExpression: { color: '#cbd5e1', fontSize: 15, marginBottom: 4 },
  savedComment: { color: '#94a3b8', fontSize: 13, fontStyle: 'italic', marginBottom: 4 },
  savedValue: { color: '#f8fafc', fontSize: 20 },
  savedMetaRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 6 },
  savedDate: { color: '#f8fafc', fontSize: 12, opacity: 0.85 },
  savedType: { color: '#f8fafc', fontSize: 11, fontWeight: '700', opacity: 0.9 },
  emptyList: { color: '#94a3b8', fontSize: 16, paddingVertical: 20 },
  closeButton: { alignItems: 'center', backgroundColor: '#22c55e', borderRadius: 5, paddingVertical: 12, flex: 1 },
  listCloseButton: { width: '100%', alignSelf: 'stretch', flex: 0 },
  tableCloseButton: { minHeight: 48, backgroundColor: '#16a34a' },
  cancelButton: { backgroundColor: '#64748b' },
  closeButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  warningBackdrop: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  warningPanel: { width: '100%', maxWidth: 420, backgroundColor: '#1e293b', borderRadius: 10, padding: 22, borderWidth: 1, borderColor: '#475569' },
  warningHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 12 },
  warningIconContainer: { width: 38, height: 38, borderRadius: 19, justifyContent: 'center', alignItems: 'center' },
  warningIconDelete: { backgroundColor: 'rgba(239, 68, 68, 0.2)' },
  warningIconChange: { backgroundColor: 'rgba(245, 158, 11, 0.2)' },
  warningIconText: { fontSize: 18 },
  warningTitle: { fontSize: 18, fontWeight: '700', color: '#f8fafc', flex: 1 },
  warningMessage: { fontSize: 14, color: '#cbd5e1', lineHeight: 21, marginBottom: 16 },
  warningPreviewBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#0f172a', borderRadius: 6, padding: 12, marginBottom: 18, borderWidth: 1, borderColor: '#334155' },
  warningPreviewCol: { flex: 1, alignItems: 'center' },
  warningPreviewLabel: { fontSize: 10, color: '#94a3b8', textTransform: 'uppercase', fontWeight: '700', marginBottom: 4 },
  warningPreviewOld: { fontSize: 15, color: '#ef4444', fontWeight: '600', textDecorationLine: 'line-through' },
  warningPreviewArrow: { fontSize: 18, color: '#94a3b8', paddingHorizontal: 8 },
  warningPreviewNew: { fontSize: 15, color: '#22c55e', fontWeight: '700' },
  warningActions: { flexDirection: 'row', gap: 12 },
  warningCancelButton: { backgroundColor: '#475569', borderRadius: 5, paddingVertical: 12, flex: 1, alignItems: 'center' },
  warningCancelText: { color: '#f8fafc', fontSize: 15, fontWeight: '600' },
  warningConfirmButton: { backgroundColor: '#22c55e', borderRadius: 5, paddingVertical: 12, flex: 1, alignItems: 'center' },
  warningConfirmButtonDelete: { backgroundColor: '#ef4444', borderRadius: 5, paddingVertical: 12, flex: 1, alignItems: 'center' },
  warningConfirmText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  commentModalBackdrop: { flex: 1, backgroundColor: 'rgba(15, 23, 42, 0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  commentModalPanel: { width: '100%', maxWidth: 500, backgroundColor: '#1e293b', borderRadius: 10, padding: 22, borderWidth: 1, borderColor: '#475569' },
  commentModalTitle: { fontSize: 18, fontWeight: '700', color: '#f8fafc', marginBottom: 16 },
  commentModalInput: { backgroundColor: '#0f172a', borderColor: '#475569', borderWidth: 1, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 12, color: '#f8fafc', fontSize: 15, minHeight: 120, textAlignVertical: 'top', marginBottom: 16 },
  commentModalActions: { flexDirection: 'row', gap: 12 },
  commentModalCancelButton: { backgroundColor: '#475569', borderRadius: 5, paddingVertical: 12, flex: 1, alignItems: 'center' },
  commentModalSaveButton: { backgroundColor: '#3b82f6', borderRadius: 5, paddingVertical: 12, flex: 1, alignItems: 'center' },
  commentModalButtonText: { color: '#ffffff', fontSize: 15, fontWeight: '700' },
  cellPressable: { flex: 1, backgroundColor: 'rgba(30, 41, 59, 0.8)', borderRadius: 4, borderWidth: 1, borderColor: '#334155', paddingHorizontal: 8, paddingVertical: 6, minHeight: 34, height: 34, justifyContent: 'center' },
  cellPressableText: { color: '#f8fafc', fontSize: 13, lineHeight: 16 },
});

